version: "3"
services:
  baseapplication:
    build: ./BaseApplication
    ports:
      - "9000:9000"
    volumes:
      - ./estilos:/estilos
  navigation:
    build: ./navigation
    ports:
      - "9001:9001"
    volumes:
      - ./estilos:/estilos
  landing:
    build: ./landing
    ports:
      - "9002:9002"
    volumes:
      - ./estilos:/estilos
  venta:
    build: ./venta
    ports:
      - "9003:9003"
    volumes:
      - ./estilos:/estilos
  alquiler:
    build: ./alquiler
    ports:
      - "9004:9004"
    volumes:
      - ./estilos:/estilos
